/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package assignment2;

/**
 *
 * @author nehiroguz
 */
// A specialized subclass that represents a location with geographical coordinates and a population count
public class PopulatedPlace extends LocatedPlace {
    // Private variable specifically for holding the population data
    private int population;
    
    // Constructor that passes coordinates and location data to the parent class, then sets the population
    public PopulatedPlace(int population, double latitude, double longitude, String zipcode, String town, String state) {
        super(latitude, longitude, zipcode, town, state);
        this.population = population;
    }

    public int getPopulation() {
        return population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    // Appends the population data to the existing string format generated by the parent class
    @Override
    public String toString() {
        return super.toString() + ", " + population;
    }   
}
